service: aws-node-express-api

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"

functions:
  api:
    handler: index.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: GET

plugins:
  - serverless-offline
custom:
  serverless-offline:
    noPrependStageInUrl: true
